### ISSUE TITLE
[doc] Google analytics tag interferes with env var link

### ISSUE THREAD

**Issue by judithpatudith** [terraform-providers/terraform-provider-consul#170]
### Description
At the bottom of the [docs front page](https://registry.terraform.io/providers/hashicorp/consul/2.6.1/docs) the link to Consul's environment variable documentation is broken. 

### Expected Behavior
I expected to go here: 
https://www.consul.io/docs/commands/index.html#environment-variables

### Actual Behavior
Google Analytics added a tracking tag that got between URL and anchor link, resulting in a 404: 
https://www.consul.io/docs/commands/index?&_ga=2.165668351.1566802157.1576266579-2016951225.1550608660#environment-variables

**Comment by remilapeyre** [comment]
Hi @judithpatudith, the link looks fine at https://www.terraform.io/docs/providers/consul/index.html, is this a bug in our documentation or in the way the docs at https://registry.terraform.io/providers/hashicorp/consul/2.6.1/docs are made?

**Comment by judithpatudith** [comment]
Hey @remilapeyre, yup the link would be fine if Google Analytics didn't add the tag. This is probably the wrongest spot for me to have filed this bug, but if you wanted to fix the link, for now, the thing to do would be to remove the `#environment-variables` section tag. 

I bet we use anchor links a bunch of places in the registry docs, so there should be a broader fix for those links. I'll ask around in Terraform Land, so leaving the link the same should eventually be fine. Thanks!

**Comment by remilapeyre** [comment]
I'm not sure if just removing the tag will work, the docs at https://registry.terraform.io/providers/hashicorp/consul/2.6.1/docs are built for each version so it must be built based on the corresponding git tag, right?

**Comment by judithpatudith** [comment]
🤦‍♀️ Yup!

**Comment by judithpatudith** [comment]
This is fixed 🎉 Closing the issue.

**Comment by findkim** [comment]
Hi! I dug into this a bit more and turns out this is a Terraform Registry bug in how the links were processed before rendering the Markdown. 

The broken link is due to the improperly removed `.html` extension from the page slug `index.html`.
* https://www.consul.io/docs/commands/index?&_ga=2.165668351.1566802157.1576266579-2016951225.1550608660#environment-variables
* https://www.consul.io/docs/commands/index.html?&_ga=2.165668351.1566802157.1576266579-2016951225.1550608660#environment-variables

This should be fixed now when you visit https://registry.terraform.io/providers/hashicorp/consul/2.6.1/docs. Thanks @judithpatudith for calling my attention to this bug
