### ISSUE TITLE
Destroy operation does not remove consul key resources

### ISSUE THREAD

**Issue by btyler97** [terraform-providers/terraform-provider-consul#63]
There is a closed issue regarding this ( #35 ), but I have a question about the choice of the implementation.

Why is a "delete" argument necessary? If I'm running a destroy, I expect all of the resources to be destroyed. I don't understand why you explicitly have to flag them as "delete." 

The plan and destroy output even indicate that the resource is going to be and was destroyed respectively.

**Comment by remilapeyre** [comment]
Hi @btyler97, I'm not familiar with the history of terraform nor am I a member of Hashicorp who could give you a detailed explanation, but since you did not receive an answer, I can try an explanation.

The `delete` attribute has been added very soon to Consul provider, at a time where data sources were not yet available.

At that time, the keys resource was used to read data from Consul and this is still supported today (but deprecated): https://www.terraform.io/docs/providers/consul/r/keys.html#deprecated-key-arguments

Looking at the code at that time (https://github.com/hashicorp/terraform/blob/c6a165f8c6c69de03aa8f7aab3ffc188cfe49f1b/builtin/providers/consul/resource_consul_keys.go#L120-L124) it seems that the delete keyword was used to know whether a particular key was managed by terraform and should be destroyed, or it was used to read data from Consul and therefore should not be destroyed.

The delete keyword should not be necessary today but is kept for backward compatibility. Changing that would require a major version change of the provider.

I hope this makes sense to you, and again, I want to say that this is what I could piece together looking at the git log and that I may be totally wrong.
